### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by ghost** [vfaddey/ITMO_java_labs#1]
Reviewer contact: https://t.me/strok1n

1. Класс base.Human имеет следующие методы, в которых просто вызывается System.out.println: lough (you mean laugh), shout, voice, sayToOnLanguage, ... . Таких методов не должно быть, нужно придумать еще какие-нибудь свойства или объекты, с которыми эти методы будут взаимодействовать. В целом в программе очень много таких методов.
2. Class body.Body has a public fields: hands, and legs. This breaks encapsulation, so make this fields private. Class base.Human also has public fields.
3. Неясно зачем в абстрактном классе abstractions.Creature поле location сделано приватным, выглядит так, будто оно должно быть protected.
4. В классе abstractions.Creature методы voice, sleep, wakeUp, ..., сделаны protected, но в классе base.Human, который наследует класс abstractions.Creature, эти же методы переопределяются с модификатором доступа public.
5. (In my opinion) Перечисление должно обозначать одно единственное свойство, которое оно градуирует. В данной программе я бы разделил перечисление Characteristics на несколько, которые бы назвал, например: уровень силы, уровень жажды, уровень страха, уровень счастья и т.д. Код станет гораздо более читабельным. Как мне кажется, это нарушает Single responsibility principle. То же относится к перечислению ItemType.
6. (In my opinion) Circular dependency between two classes is bad (Location and Creature), so I would break it.

**Comment by vfaddey** [comment]
Исправлено
Ссылка на коммит: https://github.com/vfaddey/ITMO_java_labs/commit/b5a067b2b0d5462fafadcfe11f777d630c6b1053#diff-b9cce7d8c7c8f62d2d5a6555dd3b9c82b03b3912cb51e937ad07db515331bdadR19

**Comment by vfaddey** [comment]
https://github.com/vfaddey/ITMO_java_labs/compare/afterReview?expand=1

**Comment by vfaddey** [comment]
#https://github.com/vfaddey/ITMO_java_labs/commit/b5a067b2b0d5462fafadcfe11f777d630c6b1053#diff-b9cce7d8c7c8f62d2d5a6555dd3b9c82b03b3912cb51e937ad07db515331bdadR19
