### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Sat1l** [vfaddey/ITMO_java_labs#2]
## Human.java

https://github.com/vfaddey/ITMO_java_labs/blob/4b8477d4db6b9fb2c72d0f93992e01be11135008/src/base/Human.java#L230-L235

Непонятно,  почему человек ответственнен за вывод инвентаря. Логичней чтобы человек мог только вернуть состовляющие своего инвентаря, а остальная обработка (форматирование и красивый вывод), была не на его стороне

https://github.com/vfaddey/ITMO_java_labs/blob/4b8477d4db6b9fb2c72d0f93992e01be11135008/src/base/Human.java#L277-L279

Нет смысла обращаться к характеристикам, так как эта строка все равно выводится только когда человек на коленях

##BodyPart.java & ./src/body/parts

В BodyPart определяется метод getState
https://github.com/vfaddey/ITMO_java_labs/blob/4b8477d4db6b9fb2c72d0f93992e01be11135008/src/abstractions/BodyPart.java#L40

Но во всех дальнейших его имплементациях он все равно возвращает null, толк не понятен
https://github.com/vfaddey/ITMO_java_labs/blob/4b8477d4db6b9fb2c72d0f93992e01be11135008/src/body/Body.java#L34-L37
https://github.com/vfaddey/ITMO_java_labs/blob/4b8477d4db6b9fb2c72d0f93992e01be11135008/src/body/parts/Hands.java#L41-L44
https://github.com/vfaddey/ITMO_java_labs/blob/4b8477d4db6b9fb2c72d0f93992e01be11135008/src/body/parts/Head.java#L213-L216
https://github.com/vfaddey/ITMO_java_labs/blob/4b8477d4db6b9fb2c72d0f93992e01be11135008/src/body/parts/Legs.java#L56-L59

## Language.java
https://github.com/vfaddey/ITMO_java_labs/blob/4b8477d4db6b9fb2c72d0f93992e01be11135008/src/enums/Language.java#L14
Скорее всего просто опечатка, но semicolon тут лишний

**Comment by vfaddey** [comment]
https://github.com/vfaddey/ITMO_java_labs/commit/2d8edce891c6702bc072a8b365f491fbe390bb79
https://github.com/vfaddey/ITMO_java_labs/commit/24cfc90cca0a4853b2844e69be72f3ec6b6c14a1
